import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/mcp-setup-cursor',
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user-guide/interface-and-canvas',
        'user-guide/sidebar',
        'user-guide/creating-pipelines',
        'user-guide/running-pipelines',
        'user-guide/preview-system',
        'user-guide/feedback',
        {
          type: 'category',
          label: 'Preview System',
          items: [
            'preview-system/modal-interface',
            'preview-system/guides-and-grid',
            'preview-system/video-monitors',
            'preview-system/audio-monitors',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Node Reference',
      items: [
        'node-reference/ff_a_compressor',
        'node-reference/ff_a_deesser',
        'node-reference/ff_a_delay',
        'node-reference/ff_a_echo',
        'node-reference/ff_a_equalizer',
        'node-reference/ff_a_fade',
        'node-reference/ff_a_highpass',
        'node-reference/ff_a_limiter',
        'node-reference/ff_a_loop',
        'node-reference/ff_a_lowpass',
        'node-reference/ff_a_pad',
        'node-reference/ff_a_reverse',
        'node-reference/ff_a_setrate',
        'node-reference/ff_a_tempo',
        'node-reference/ff_a_volume',
        'node-reference/ff_aspect_ratio',
        'node-reference/ff_audio',
        'node-reference/ff_avgblur',
        'node-reference/ff_blur',
        'node-reference/ff_boxblur',
        'node-reference/ff_colorchannelmixer',
        'node-reference/ff_colorcorrect',
        'node-reference/ff_colorize',
        'node-reference/ff_colorkey',
        'node-reference/ff_colorlevels',
        'node-reference/ff_colortemperature',
        'node-reference/ff_colour_adjust',
        'node-reference/ff_colour_balance',
        'node-reference/ff_colour_contrast',
        'node-reference/ff_concat',
        'node-reference/ff_convert',
        'node-reference/ff_crop',
        'node-reference/ff_custom',
        'node-reference/ff_cut',
        'node-reference/ff_dblur',
        'node-reference/ff_download',
        'node-reference/ff_drawbox',
        'node-reference/ff_exposure',
        'node-reference/ff_extract_frames',
        'node-reference/ff_flip',
        'node-reference/ff_fps',
        'node-reference/ff_gblur',
        'node-reference/ff_grep',
        'node-reference/ff_grouptime',
        'node-reference/ff_hue',
        'node-reference/ff_huesaturation',
        'node-reference/ff_image',
        'node-reference/ff_input',
        'node-reference/ff_lut',
        'node-reference/ff_middle',
        'node-reference/ff_negate',
        'node-reference/ff_orientation',
        'node-reference/ff_output',
        'node-reference/ff_overlay',
        'node-reference/ff_pad',
        'node-reference/ff_perspective',
        'node-reference/ff_proxy',
        'node-reference/ff_rotate',
        'node-reference/ff_scale',
        'node-reference/ff_sharpen',
        'node-reference/ff_smartblur',
        'node-reference/ff_stack',
        'node-reference/ff_subtitles',
        'node-reference/ff_text',
        'node-reference/ff_thumbnail',
        'node-reference/ff_transcode',
        'node-reference/ff_transition',
        'node-reference/ff_unsharp',
        'node-reference/ff_vibrance',
        'node-reference/ff_watch',
        'node-reference/ff_watermark',
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      items: [
        'settings/file',
        'settings/style',
        'settings/logs',
        'settings/keys',
        'settings/info',
        'settings/mcp',
        'settings/output',
        'settings/plugins',
        'settings/license',
      ],
    },
    {
      type: 'category',
      label: 'The Data Store',
      items: [
        'data-store/introduction',
        'data-store/file-data',
        'data-store/system',
        'data-store/random',
        'data-store/nodes',
        'data-store/custom',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/template-variables',
        'advanced/layout-management',
        'advanced/custom-nodes',
        'advanced/mcp-integration',
        'advanced/pipeline-validation',
      ],
    },
    {
      type: 'category',
      label: 'JSON Code',
      items: [
        'json-code/json-format',
      ],
    },
    {
      type: 'category',
      label: 'Technical Details',
      items: [
        'technical-details/architecture',
        'technical-details/ffmpeg-integration',
        'technical-details/workflow-execution',
      ],
    },
    'debugging',
    {
      type: 'category',
      label: 'Extending Plugins',
      items: [
        'extending-plugins/introduction',
      ],
    },
  ],
};

export default sidebars;
