/**
 * Mapping of node IDs to their icon paths
 * This is used to display icons next to node names in the sidebar
 */

export const nodeIcons: Record<string, string> = {
  'ff_a_compressor': '/img/node-icons/audio-compressor.svg',
  'ff_a_deesser': '/img/node-icons/audio-deesser.svg',
  'ff_a_delay': '/img/node-icons/audio-delay.svg',
  'ff_a_echo': '/img/node-icons/audio-echo.svg',
  'ff_a_equalizer': '/img/node-icons/audio-equalizer.svg',
  'ff_a_fade': '/img/node-icons/audio-fade.svg',
  'ff_a_highpass': '/img/node-icons/audio-highpass.svg',
  'ff_a_limiter': '/img/node-icons/audio-limiter.svg',
  'ff_a_loop': '/img/node-icons/audio-loop.svg',
  'ff_a_lowpass': '/img/node-icons/audio-lowpass.svg',
  'ff_a_pad': '/img/node-icons/audio-pad.svg',
  'ff_a_reverse': '/img/node-icons/audio-reverse.svg',
  'ff_a_setrate': '/img/node-icons/audio-setrate.svg',
  'ff_a_tempo': '/img/node-icons/audio-tempo.svg',
  'ff_a_volume': '/img/node-icons/audio-volume.svg',
  'ff_aspect_ratio': '/img/node-icons/aspect-ratio.svg',
  'ff_audio': '/img/node-icons/audio.svg',
  'ff_avgblur': '/img/node-icons/avgblur.svg',
  'ff_blur': '/img/node-icons/blur.svg',
  'ff_boxblur': '/img/node-icons/boxblur.svg',
  'ff_colorchannelmixer': '/img/node-icons/colorchannelmixer.svg',
  'ff_colorcorrect': '/img/node-icons/colorcorrect.svg',
  'ff_colorize': '/img/node-icons/colorize.svg',
  'ff_colorkey': '/img/node-icons/colorkey.svg',
  'ff_colorlevels': '/img/node-icons/colorlevels.svg',
  'ff_colortemperature': '/img/node-icons/colortemperature.svg',
  'ff_colour_adjust': '/img/node-icons/colour-adjust.svg',
  'ff_colour_balance': '/img/node-icons/colour-balance.svg',
  'ff_colour_contrast': '/img/node-icons/colour-contrast.svg',
  'ff_concat': '/img/node-icons/concat.svg',
  'ff_convert': '/img/node-icons/convert.svg',
  'ff_crop': '/img/node-icons/crop.svg',
  'ff_custom': '/img/node-icons/custom.svg',
  'ff_cut': '/img/node-icons/cut.svg',
  'ff_dblur': '/img/node-icons/dblur.svg',
  'ff_download': '/img/node-icons/download.svg',
  'ff_drawbox': '/img/node-icons/drawbox.svg',
  'ff_exposure': '/img/node-icons/exposure.svg',
  'ff_extract_frames': '/img/node-icons/extract-frames.svg',
  'ff_flip': '/img/node-icons/flip.svg',
  'ff_fps': '/img/node-icons/fps.svg',
  'ff_gblur': '/img/node-icons/gblur.svg',
  'ff_grep': '/img/node-icons/grep.svg',
  'ff_grouptime': '/img/node-icons/grouptime.svg',
  'ff_hue': '/img/node-icons/hue.svg',
  'ff_huesaturation': '/img/node-icons/huesaturation.svg',
  'ff_image': '/img/node-icons/image.svg',
  'ff_input': '/img/node-icons/input.svg',
  'ff_lut': '/img/node-icons/lut.svg',
  'ff_middle': '/img/node-icons/middle.svg',
  'ff_negate': '/img/node-icons/negate.svg',
  'ff_orientation': '/img/node-icons/orientation.svg',
  'ff_output': '/img/node-icons/output.svg',
  'ff_overlay': '/img/node-icons/overlay.svg',
  'ff_pad': '/img/node-icons/pad.svg',
  'ff_perspective': '/img/node-icons/perspective.svg',
  'ff_proxy': '/img/node-icons/proxy.svg',
  'ff_rotate': '/img/node-icons/rotate.svg',
  'ff_scale': '/img/node-icons/scale.svg',
  'ff_sharpen': '/img/node-icons/sharpen.svg',
  'ff_smartblur': '/img/node-icons/smartblur.svg',
  'ff_stack': '/img/node-icons/stack.svg',
  'ff_subtitles': '/img/node-icons/subtitles.svg',
  'ff_text': '/img/node-icons/text.svg',
  'ff_thumbnail': '/img/node-icons/thumbnail.svg',
  'ff_transcode': '/img/node-icons/transcode.svg',
  'ff_transition': '/img/node-icons/transition.svg',
  'ff_unsharp': '/img/node-icons/unsharp.svg',
  'ff_vibrance': '/img/node-icons/vibrance.svg',
  'ff_watch': '/img/node-icons/watch.svg',
  'ff_watermark': '/img/node-icons/watermark.svg',
};

/**
 * Get icon path for a node ID
 */
export function getNodeIcon(nodeId: string): string | undefined {
  return nodeIcons[nodeId];
}
