#!/bin/bash
# List of remaining nodes to process (after the first 20)
# This is a reference list - actual processing happens via Electron automation

completed=(
  "ff_a_fade"
  "ff_a_compressor"
  "ff_a_deesser"
  "ff_a_delay"
  "ff_a_echo"
  "ff_a_equalizer"
  "ff_a_highpass"
  "ff_a_limiter"
  "ff_a_loop"
  "ff_a_lowpass"
  "ff_a_pad"
  "ff_a_reverse"
  "ff_a_setrate"
  "ff_a_tempo"
  "ff_a_volume"
  "ff_aspect_ratio"
  "ff_audio"
  "ff_avgblur"
  "ff_blur"
)

remaining=(
  "Box Blur:ff_boxblur"
  "Color Channel Mixer:ff_colorchannelmixer"
  "Color Correct:ff_colorcorrect"
  "Colorize:ff_colorize"
  "Colorkey (Chroma Key):ff_colorkey"
  "Color Levels:ff_colorlevels"
  "Color Temperature:ff_colortemperature"
  "Colour Adjust:ff_colour_adjust"
  "Colour Balance:ff_colour_balance"
  "Colour Contrast:ff_colour_contrast"
  "Concatenate Videos:ff_concat"
  "Convert Format:ff_convert"
  "Crop Video:ff_crop"
  "Custom FFMPEG:ff_custom"
  "Cut Video:ff_cut"
  "Directional Blur:ff_dblur"
  "Download:ff_download"
  "Draw Box:ff_drawbox"
  "Exposure:ff_exposure"
  "Extract Frames:ff_extract_frames"
  "Flip Video:ff_flip"
  "Change FPS:ff_fps"
  "Gaussian Blur:ff_gblur"
  "File Filter:ff_grep"
  "Group Time:ff_grouptime"
  "Hue:ff_hue"
  "Hue Saturation:ff_huesaturation"
  "Image to Video:ff_image"
  "Input:ff_input"
  "LUT Color Grading:ff_lut"
  "Extract Middle:ff_middle"
  "Negate (Invert):ff_negate"
  "Orientation:ff_orientation"
  "Output:ff_output"
  "Overlay:ff_overlay"
  "Pad Video:ff_pad"
  "Perspective:ff_perspective"
  "Generate Proxy:ff_proxy"
  "Rotate Video:ff_rotate"
  "Scale Video:ff_scale"
  "Sharpen Video:ff_sharpen"
  "Smart Blur:ff_smartblur"
  "Stack Videos:ff_stack"
  "Subtitles:ff_subtitles"
  "Add Text:ff_text"
  "Thumbnail:ff_thumbnail"
  "Transcode Video:ff_transcode"
  "Video Transitions:ff_transition"
  "Unsharp Mask:ff_unsharp"
  "Vibrance:ff_vibrance"
  "Watch Folder:ff_watch"
  "Watermark:ff_watermark"
)

echo "Remaining nodes: ${#remaining[@]}"
